repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.13.1-1
    hooks:
      - id: shfmt
        args: ["-w", "-s", "-ln", "bash"]
        exclude: '.*_out\.sh$|^emitted_.*\.sh$'

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: [
          "-e",
          "SC2106,SC2086,SC2000,SC2094,SC1091,SC2016,SC2129,SC3054,SC3040,SC2059,SC2148,SC2155,SC2181,SC3043,SC2296,SC3028"
        ]
        exclude: '.*_out\.sh$|^emitted_.*\.sh$'

  - repo: local
    hooks:
      - id: make-build
        name: Build
        entry: make build
        language: system
        pass_filenames: false

      - id: make-test
        name: Test
        entry: make test
        language: system
        pass_filenames: false

      - id: update-badges
        name: Update Badges (Doc & Test Coverage)
        entry: python3 scripts/update_badges.py
        language: system
        pass_filenames: false
        always_run: true

      - id: swagger-2-petstore
        name: Swagger 2.0 Petstore Test
        entry: bash -c 'python3 -c "import yaml, json, sys; json.dump(yaml.safe_load(sys.stdin), sys.stdout)" < ../petstore.json > temp-sh-spec.json && ./cdd.sh from_openapi -i temp-sh-spec.json -o temp-sh-dir && ./cdd.sh to_openapi -i temp-sh-dir -o temp-sh-out.json && rm -rf temp-sh-spec.json temp-sh-dir temp-sh-out.json ast.json'
        language: system
        pass_filenames: false

      - id: openapi-3-petstore
        name: OpenAPI 3.2.0 Petstore Test
        entry: bash -c 'python3 -c "import yaml, json, sys; json.dump(yaml.safe_load(sys.stdin), sys.stdout)" < ../petstore_oas3.json > temp-sh-spec.json && ./cdd.sh from_openapi -i temp-sh-spec.json -o temp-sh-dir && ./cdd.sh to_openapi -i temp-sh-dir -o temp-sh-out.json && rm -rf temp-sh-spec.json temp-sh-dir temp-sh-out.json ast.json'
        language: system
        pass_filenames: false

      - id: make-build-wasm
        name: Build WASM
        entry: make build_wasm
        language: system
        pass_filenames: false

