repos:
-   repo: local
    hooks:
    -   id: tests
        name: Run test.sh
        entry: ./test.sh
        language: system
        pass_filenames: false
    -   id: shields
        name: Update Shields
        entry: ./update_shields.sh
        language: system
        pass_filenames: false
    -   id: git-add-readme
        name: Git Add README.md
        entry: git add README.md
        language: system
        pass_filenames: false
